const captions = {
  peek: (from, to, genero) => from === to ? 'está espiando detrás de una puerta como Alastor planeando algo.' : `está acechando desde las sombras a`,
  comfort: (from, to) => (from === to ? 'se está dando ánimos porque el Infierno es duro.' : 'está intentando consolar (a su manera) a'),
  thinkhard: (from, to) => from === to ? 'está procesando una idea tan loca como las de Charlie.' : 'está analizando cada pecado de',
  curious: (from, to) => from === to ? 'tiene una curiosidad nivel "Vaggie sospechando de todos".' : 'siente una curiosidad peligrosa por lo que hace',
  sniff: (from, to) => from === to ? 'está olfateando el aire... ¿huele a redención o a azufre?' : 'está olfateando descaradamente a',
  stare: (from, to) => from === to ? 'se quedó con la mirada perdida como Husk tras una noche de bar.' : 'se le queda mirando fijamente a',
  trip: (from, to) => from === to ? 'se tropezó con su propio ego, ¡qué espectáculo!' : 'tropezó accidentalmente (¿o no?) con',
  blowkiss: (from, to) => (from === to ? 'se lanza un beso al espejo, ¡derrochando estilo!' : 'le lanzó un beso pecaminoso a'),
  snuggle: (from, to) => from === to ? 'se acurruca con un peluche de Keekee.' : 'se acurruca dulcemente (y sin que Vaggie vea) con',
  sleep: (from, to, genero) => from === to ? 'cayó en un sueño profundo tras una purga.' : 'se quedó a dormir (sin pagar renta) con',
  cold: (from, to, genero) => (from === to ? 'siente el frío de una noche solitaria en el Hazbin Hotel.' : 'busca calorcito pegándose a'),
  sing: (from, to, genero) => (from === to ? 'empezó un número musical improvisado.' : 'le está cantando una canción de redención a'),
  tickle: (from, to, genero) => from === to ? 'se está riendo por puro nerviosismo.' : 'le está haciendo cosquillas infernales a',
  scream: (from, to, genero) => (from === to ? 'está pegando un grito que despertaría a los Overlords.' : 'le está gritando sus verdades a'),
  push: (from, to, genero) => (from === to ? 'se empujó al abismo del sarcasmo.' : 'le dio un empujón digno de Angel Dust a'),
  nope: (from, to, genero) => (from === to ? 'dice "¡Ni hablar!", ni que fuera una oferta de Alastor.' : 'le dice un rotundo "¡NO!" a'),
  jump: (from, to, genero) => (from === to ? 'salta de alegría como Charlie con un nuevo huésped.' : 'salta de emoción junto a'),
  heat: (from, to, genero) => (from === to ? 'siente que el calor del Infierno está subiendo de nivel.' : 'se está sofocando por culpa de'),
  gaming: (from, to, genero) => (from === to ? 'está apostando su alma en un juego solitario.' : 'está perdiendo sus ahorros jugando con'),
  draw: (from, to, genero) => (from === to ? 'hace un dibujo... ¿eso es un retrato de Lucifer?' : 'está dibujando algo muy cuestionable sobre'),
  call: (from, to, genero) => from === to ? 'está llamando a soporte técnico del Cielo.' : 'está acosando telefónicamente a',
  seduce: (from, to, genero) => from === to ? 'está practicando sus dotes de seducción frente al vacío.' : 'está usando todo su encanto de estrella porno con',
  shy: (from, to, genero) => from === to ? `se sonrojó más que Sir Pentious tras un cumplido.` : `se siente demasiado ${genero === 'Hombre' ? 'tímido' : genero === 'Mujer' ? 'tímida' : 'tímide'} para ver a los ojos a`,
  slap: (from, to, genero) => from === to ? `se dio una bofetada para reaccionar.` : 'le dio un bofetón de realidad a',
  bath: (from, to) => (from === to ? 'se está bañando en las aguas del Infierno.' : 'está intentando bañar (a la fuerza) a'),
  angry: (from, to, genero) => from === to ? `está más ${genero === 'Hombre' ? 'enojado' : genero === 'Mujer' ? 'enojada' : 'enojadx'} que Vaggie sin café.` : `está sacando sus garras contra`,
  bored: (from, to, genero) => from === to ? `está más ${genero === 'Hombre' ? 'aburrido' : genero === 'Mujer' ? 'aburrida' : 'aburridx'} que Husk en la recepción.` : `se aburrió de la existencia de`,
  bite: (from, to, genero) => from === to ? `se mordió por accidente, ¡ay!` : 'le dio una mordidita juguetona (o caníbal) a',
  bleh: (from, to) => from === to ? 'está haciendo muecas como Niffty persiguiendo bichos.' : 'le está sacando la lengua con descaro a',
  bonk: (from, to, genero) => from === to ? `se dio un golpe por andar de distraídx.` : 'le dio un bonk en la cabeza a',
  blush: (from, to) => (from === to ? 'se puso tan rojo como el traje de Alastor.' : 'se sonrojó por los comentarios de'),
  impregnate: (from, to) => (from === to ? 'está en espera de un pequeño demonio.' : 'decidió que era buen momento para preñar a'),
  bully: (from, to, genero) => from === to ? `se está autosaboteando, ¡necesita una charla con Charlie!` : 'le está haciendo la vida imposible a',
  cry: (from, to) => (from === to ? 'está llorando porque no hay redención hoy.' : 'está llorando en el hombro de'),
  happy: (from, to) => (from === to ? 'está más feliz que Charlie en un arcoíris.' : 'comparte su alegría infernal con'),
  coffee: (from, to) => (from === to ? 'está tomando café para aguantar este caos.' : 'está compartiendo un café negro como el alma de'),
  clap: (from, to) => (from === to ? 'aplaude con sarcasmo nivel Overlord.' : 'aplaude por el show que dio'),
  cringe: (from, to) => (from === to ? 'siente un cringe que le llega hasta el alma.' : 'siente una pena ajena increíble por'),
  dance: (from, to) => (from === to ? 'está bailando un jazz muy animado.' : 'está bailando un vals prohibido con'),
  cuddle: (from, to, genero) => from === to ? `se hizo bolita en el sofá del lobby.` : 'está buscando mimos de',
  drunk: (from, to, genero) => from === to ? `se pasó de tragos en el bar de Husk.` : `está compartiendo una borrachera épica con`,
  dramatic: (from, to) => from === to ? 'está haciendo un drama digno de una telenovela demoníaca.' : 'le está armando un berrinche a',
  handhold: (from, to, genero) => from === to ? `se agarra la mano para no sentirse ${genero === 'Hombre' ? 'solo' : genero === 'Mujer' ? 'sola' : 'solx'}.` : 'le tomó la mano con mucha confianza a',
  eat: (from, to) => (from === to ? 'está devorando algo delicioso (esperemos que no sea un pecador).' : 'está cenando con'),
  highfive: (from, to) => from === to ? 'chocó los cinco con su sombra.' : 'chocó los cinco con',
  hug: (from, to, genero) => from === to ? `necesita un abrazo de grupo urgente.` : 'le dio un abrazo muy apretado a',
  kill: (from, to) => (from === to ? 'hizo un trato que no debió y se auto-eliminó.' : 'mandó directamente al doble infierno a'),
  kiss: (from, to) => (from === to ? 'está lanzando besos al aire como una estrella.' : 'le plantó un beso a'),
  kisscheek: (from, to) => from === to ? 'se dio un beso en la mano, ¡qué egocéntrico!' : 'le dio un beso tierno en la mejilla a',
  lick: (from, to) => (from === to ? 'se lamió... ¿por qué haces eso?' : 'lamió de forma extraña a'),
  laugh: (from, to) => (from === to ? 'se ríe con malicia pura.' : 'se está burlando de las desgracias de'),
  pat: (from, to) => (from === to ? 'se acaricia el cabello sintiéndose fabuloso.' : 'le da palmaditas en la cabeza a'),
  love: (from, to, genero) => from === to ? `se ama más que Adam a sí mismo.` : 'siente un amor prohibido por',
  pout: (from, to, genero) => from === to ? `está haciendo un puchero muy tierno.` : 'está haciendo muecas frente a',
  punch: (from, to) => (from === to ? 'lanzó un golpe al aire practicando para la purga.' : 'le acomodó un buen puñetazo a'),
  run: (from, to) => (from === to ? 'corre como si lo persiguiera Sir Pentious con un rayo láser.' : 'está huyendo despavorido de'),
  scared: (from, to, genero) => from === to ? `está aterradx, ¡parece que vio a Alastor sin sonrisa!` : `está temblando de miedo por culpa de`,
  sad: (from, to) => (from === to ? `está más triste que un ángel caído.` : `le cuenta sus penas a`),
  smoke: (from, to) => (from === to ? 'está fumando como Angel Dust tras un largo día.' : 'está compartiendo un cigarrillo con'),
  smile: (from, to) => (from === to ? 'está sonriendo porque nunca se está totalmente vestido sin una.' : 'le dedicó una sonrisa cínica a'),
  spit: (from, to, genero) => from === to ? `escupió al suelo con desdén.` : 'le escupió con odio a',
  smug: (from, to) => (from === to ? 'está presumiendo su poder como un Overlord recién llegado.' : 'le presume sus lujos a'),
  think: (from, to) => from === to ? 'está planeando su ascenso al trono.' : 'está obsesionadx pensando en',
  step: (from, to, genero) => from === to ? `se pisó la cola (si tuviera).` : 'está pisoteando el orgullo de',
  wave: (from, to, genero) => from === to ? `saluda a su reflejo en el espejo de la suite.` : 'está saludando desde lejos a',
  walk: (from, to) => (from === to ? 'camina por las calles rojas de la ciudad.' : 'está dando un paseo por el Infierno con'),
  wink: (from, to, genero) => from === to ? `guiñó un ojo con mucha picardía.` : 'le lanzó un guiño seductor a',
}
